name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
    - name: Create Timestamp for version info
      id: time
      uses: nanzm/get-time-action@master
      with:
        format: 'YYYY-MM-DD-HH-mm-ss'
    - name: Make Artifact Available
      uses: actions/upload-artifact@v2
      with:
        name: "Artifact-${{steps.time.outputs.time}}"
        path: build/libs
        retention-days: 5
    - name: Deploy to AWS Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws_secret_key: ${{secrets.AWS_SECRET_KEY_ID}}
        application_name: SpringInProdApp
        environment_name: SpringInProdApp-env
        version_label: SpringInProdApp-${{steps.time.outputs.time}}
        region: us-east-1
        deployment_package: build/libs/spring-in-prod-0.0.1-SNAPSHOT.jar